/* Generated by NGPC Sound Creator - Project Audio API */
#ifndef NGPC_PROJECT_AUDIO_API_H
#define NGPC_PROJECT_AUDIO_API_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct NgpcProjectSongRef {
    const char* id;
    const char* name;
    const unsigned char* note_table;
    const unsigned char* ch0;
    const unsigned char* ch1;
    const unsigned char* ch2;
    const unsigned char* chn;
    unsigned short loop_ch0;
    unsigned short loop_ch1;
    unsigned short loop_ch2;
    unsigned short loop_chn;
} NgpcProjectSongRef;

extern const unsigned short NGPC_PROJECT_SONG_COUNT;
extern const NgpcProjectSongRef NGPC_PROJECT_SONGS[];

const NgpcProjectSongRef* NgpcProject_GetSong(unsigned short index);
void NgpcProject_BgmStartLoop4ByIndex(unsigned short index);

#ifdef __cplusplus
}
#endif

#endif /* NGPC_PROJECT_AUDIO_API_H */
