/* Generated by NGPC Sound Creator - Project Audio API */
#include "project_audio_api.h"

/* Driver entry points (sounds.c). */
extern void Bgm_SetNoteTable(const unsigned char* note_table);
extern void Bgm_StartLoop4Ex(const unsigned char* stream0, unsigned short loop0,
                             const unsigned char* stream1, unsigned short loop1,
                             const unsigned char* stream2, unsigned short loop2,
                             const unsigned char* streamN, unsigned short loopN);

#if defined(__GNUC__)
#define NGPC_PROJECT_WEAK __attribute__((weak))
#else
#define NGPC_PROJECT_WEAK
#endif
/* Link fallback only. Real table is selected per song at runtime. */
const unsigned char NOTE_TABLE[102] NGPC_PROJECT_WEAK = {
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00,
    0x01, 0x00
};

/* Song symbols come from exports/song_*.c (namespaced by export pipeline). */
extern const unsigned char PROJECT_SONG_01_NOTE_TABLE[];
extern const unsigned char PROJECT_SONG_01_BGM_CH0[];
extern const unsigned char PROJECT_SONG_01_BGM_CH1[];
extern const unsigned char PROJECT_SONG_01_BGM_CH2[];
extern const unsigned char PROJECT_SONG_01_BGM_CHN[];
extern const unsigned short PROJECT_SONG_01_BGM_CH0_LOOP;
extern const unsigned short PROJECT_SONG_01_BGM_CH1_LOOP;
extern const unsigned short PROJECT_SONG_01_BGM_CH2_LOOP;
extern const unsigned short PROJECT_SONG_01_BGM_CHN_LOOP;
extern const unsigned char PROJECT_MENU_TEST_NOTE_TABLE[];
extern const unsigned char PROJECT_MENU_TEST_BGM_CH0[];
extern const unsigned char PROJECT_MENU_TEST_BGM_CH1[];
extern const unsigned char PROJECT_MENU_TEST_BGM_CH2[];
extern const unsigned char PROJECT_MENU_TEST_BGM_CHN[];
extern const unsigned short PROJECT_MENU_TEST_BGM_CH0_LOOP;
extern const unsigned short PROJECT_MENU_TEST_BGM_CH1_LOOP;
extern const unsigned short PROJECT_MENU_TEST_BGM_CH2_LOOP;
extern const unsigned short PROJECT_MENU_TEST_BGM_CHN_LOOP;

const unsigned short NGPC_PROJECT_SONG_COUNT = 2;

const NgpcProjectSongRef NGPC_PROJECT_SONGS[] = {
    {
        "song_01",
        "Song 1",
        PROJECT_SONG_01_NOTE_TABLE,
        PROJECT_SONG_01_BGM_CH0,
        PROJECT_SONG_01_BGM_CH1,
        PROJECT_SONG_01_BGM_CH2,
        PROJECT_SONG_01_BGM_CHN,
        PROJECT_SONG_01_BGM_CH0_LOOP,
        PROJECT_SONG_01_BGM_CH1_LOOP,
        PROJECT_SONG_01_BGM_CH2_LOOP,
        PROJECT_SONG_01_BGM_CHN_LOOP
    },
    {
        "menu_test",
        "menu test",
        PROJECT_MENU_TEST_NOTE_TABLE,
        PROJECT_MENU_TEST_BGM_CH0,
        PROJECT_MENU_TEST_BGM_CH1,
        PROJECT_MENU_TEST_BGM_CH2,
        PROJECT_MENU_TEST_BGM_CHN,
        PROJECT_MENU_TEST_BGM_CH0_LOOP,
        PROJECT_MENU_TEST_BGM_CH1_LOOP,
        PROJECT_MENU_TEST_BGM_CH2_LOOP,
        PROJECT_MENU_TEST_BGM_CHN_LOOP
    },
};

const NgpcProjectSongRef* NgpcProject_GetSong(unsigned short index)
{
    if (index >= NGPC_PROJECT_SONG_COUNT) return 0;
    return &NGPC_PROJECT_SONGS[index];
}

void NgpcProject_BgmStartLoop4ByIndex(unsigned short index)
{
    const NgpcProjectSongRef* song = NgpcProject_GetSong(index);
    if (!song) return;
    Bgm_SetNoteTable(song->note_table);
    Bgm_StartLoop4Ex(song->ch0, song->loop_ch0,
                     song->ch1, song->loop_ch1,
                     song->ch2, song->loop_ch2,
                     song->chn, song->loop_chn);
}
