/* Generated by NGPC Sound Creator - Project SFX Bank */
/* index -> name mapping is in comments below */

const unsigned char PROJECT_SFX_COUNT = 7;

const unsigned char PROJECT_SFX_TONE_ON[] = {1, 0, 1, 1, 1, 1, 1};
const unsigned char PROJECT_SFX_TONE_CH[] = {1, 0, 0, 0, 1, 0, 2};
const unsigned short PROJECT_SFX_TONE_DIV[] = {130, 220, 320, 320, 130, 220, 300};
const unsigned char PROJECT_SFX_TONE_ATTN[] = {0, 2, 0, 0, 2, 2, 0};
const unsigned char PROJECT_SFX_TONE_FRAMES[] = {12, 2, 4, 7, 12, 3, 10};
const unsigned char PROJECT_SFX_TONE_SW_ON[] = {1, 0, 1, 1, 1, 0, 1};
const unsigned short PROJECT_SFX_TONE_SW_END[] = {280, 220, 280, 220, 280, 220, 230};
const signed short PROJECT_SFX_TONE_SW_STEP[] = {5, 1, -4, -6, 5, 1, -40};
const unsigned char PROJECT_SFX_TONE_SW_SPEED[] = {1, 1, 2, 2, 1, 1, 1};
const unsigned char PROJECT_SFX_TONE_SW_PING[] = {0, 0, 0, 0, 0, 0, 1};
const unsigned char PROJECT_SFX_TONE_ENV_ON[] = {1, 0, 1, 1, 1, 0, 0};
const unsigned char PROJECT_SFX_TONE_ENV_STEP[] = {2, 1, 1, 1, 2, 1, 2};
const unsigned char PROJECT_SFX_TONE_ENV_SPD[] = {2, 1, 2, 3, 2, 1, 1};
const unsigned char PROJECT_SFX_NOISE_ON[] = {1, 1, 0, 0, 1, 1, 0};
const unsigned char PROJECT_SFX_NOISE_RATE[] = {0, 1, 1, 1, 0, 3, 1};
const unsigned char PROJECT_SFX_NOISE_TYPE[] = {1, 1, 1, 1, 1, 1, 0};
const unsigned char PROJECT_SFX_NOISE_ATTN[] = {0, 0, 10, 10, 0, 0, 7};
const unsigned char PROJECT_SFX_NOISE_FRAMES[] = {20, 10, 0, 0, 25, 10, 4};
const unsigned char PROJECT_SFX_NOISE_BURST[] = {1, 1, 0, 0, 1, 1, 0};
const unsigned char PROJECT_SFX_NOISE_BURST_DUR[] = {4, 1, 1, 1, 5, 7, 1};
const unsigned char PROJECT_SFX_NOISE_ENV_ON[] = {1, 1, 0, 0, 1, 1, 0};
const unsigned char PROJECT_SFX_NOISE_ENV_STEP[] = {2, 2, 1, 1, 1, 3, 2};
const unsigned char PROJECT_SFX_NOISE_ENV_SPD[] = {3, 2, 1, 1, 2, 4, 1};
const unsigned char PROJECT_SFX_TONE_ADSR_ON[] = {0, 0, 0, 0, 0, 0, 0};
const unsigned char PROJECT_SFX_TONE_ADSR_AR[] = {0, 0, 0, 0, 0, 0, 0};
const unsigned char PROJECT_SFX_TONE_ADSR_DR[] = {0, 0, 0, 0, 0, 0, 0};
const unsigned char PROJECT_SFX_TONE_ADSR_SL[] = {0, 0, 0, 0, 0, 0, 0};
const unsigned char PROJECT_SFX_TONE_ADSR_SR[] = {0, 0, 0, 0, 0, 0, 0};
const unsigned char PROJECT_SFX_TONE_ADSR_RR[] = {0, 0, 0, 0, 0, 0, 0};
const unsigned char PROJECT_SFX_TONE_LFO1_ON[] = {0, 0, 0, 0, 0, 0, 0};
const unsigned char PROJECT_SFX_TONE_LFO1_WAVE[] = {0, 0, 0, 0, 0, 0, 0};
const unsigned char PROJECT_SFX_TONE_LFO1_HOLD[] = {0, 0, 0, 0, 0, 0, 0};
const unsigned char PROJECT_SFX_TONE_LFO1_RATE[] = {0, 0, 0, 0, 0, 0, 0};
const unsigned char PROJECT_SFX_TONE_LFO1_DEPTH[] = {0, 0, 0, 0, 0, 0, 0};
const unsigned char PROJECT_SFX_TONE_LFO2_ON[] = {0, 0, 0, 0, 0, 0, 0};
const unsigned char PROJECT_SFX_TONE_LFO2_WAVE[] = {0, 0, 0, 0, 0, 0, 0};
const unsigned char PROJECT_SFX_TONE_LFO2_HOLD[] = {0, 0, 0, 0, 0, 0, 0};
const unsigned char PROJECT_SFX_TONE_LFO2_RATE[] = {0, 0, 0, 0, 0, 0, 0};
const unsigned char PROJECT_SFX_TONE_LFO2_DEPTH[] = {0, 0, 0, 0, 0, 0, 0};
const unsigned char PROJECT_SFX_TONE_LFO_ALGO[] = {0, 0, 0, 0, 0, 0, 0};

/* 0: explosion */
/* 1: tir_vaisseau */
/* 2: menu_move */
/* 3: menu_select */
/* 4: explosion_new */
/* 5: tir_vaisseau_new */
/* 6: catch_power_up */
