/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 shmup_enemy5_fat_tiles_count = 32u;
const u16 shmup_enemy5_fat_tiles[] = {
    0x0015, 0x0006, 0x001A, 0x056F, 0x01AD, 0x06DA, 0x1B55, 0x6A7F, 0x5554, 0xAAA9, 0x6A64, 0x5564,
    0xA690, 0x5640, 0xFE40, 0xFE40, 0x6A7F, 0x1B55, 0x06DA, 0x01AD, 0x056F, 0x001A, 0x0006, 0x0015,
    0xFE40, 0xFE40, 0x5640, 0xA690, 0x5564, 0x6A64, 0xAAA9, 0x5554
};

const u8 shmup_enemy5_fat_palette_count = 1u;
const u16 shmup_enemy5_fat_palettes[] = {
    0x0000, 0x0000, 0x0527, 0x00AF
};

const u8 shmup_enemy5_fat_pal_base = 7u;

const u16 shmup_enemy5_fat_tile_base = 292u;

const NgpcMetasprite shmup_enemy5_fat_frame_0 = {
    4u, 16u, 16u,
    {
        { 0, 0, 292, 7, 0 },
        { 8, 0, 293, 7, 0 },
        { 0, 8, 294, 7, 0 },
        { 8, 8, 295, 7, 0 }
    }
};

const MsprAnimFrame shmup_enemy5_fat_anim[] = {
    { &shmup_enemy5_fat_frame_0, 6 }
};

const u8 shmup_enemy5_fat_anim_count = 1u;
