/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef SHMUP_DROP_FINAL_MSPR_H
#define SHMUP_DROP_FINAL_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 shmup_drop_final_tiles_count;
extern const u16 shmup_drop_final_tiles[];

extern const u8 shmup_drop_final_palette_count;
extern const u16 shmup_drop_final_palettes[];
extern const u8 shmup_drop_final_pal_base;
extern const u16 shmup_drop_final_tile_base;

extern const NgpcMetasprite shmup_drop_final_frame_0;

extern const MsprAnimFrame shmup_drop_final_anim[];
extern const u8 shmup_drop_final_anim_count;

#endif /* SHMUP_DROP_FINAL_MSPR_H */
