/* Generated by ngpc_tilemap.py - do not edit */

#ifndef SHMUP_HUDBAR_TILEMAP_H
#define SHMUP_HUDBAR_TILEMAP_H

#include "ngpc_types.h"

extern const u8 shmup_hudbar_map_w;
extern const u8 shmup_hudbar_map_h;
extern const u16 shmup_hudbar_map_len;

extern const u8 shmup_hudbar_palette_count;
extern const u16 shmup_hudbar_palettes[];

extern const u16 shmup_hudbar_tiles_count;
extern const u16 shmup_hudbar_tiles[];

extern const u16 shmup_hudbar_map_tiles[];
extern const u8 shmup_hudbar_map_pals[];

#endif /* SHMUP_HUDBAR_TILEMAP_H */
