/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef SHMUP_BULLET_MSPR_H
#define SHMUP_BULLET_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 shmup_bullet_tiles_count;
extern const u16 shmup_bullet_tiles[];

extern const u8 shmup_bullet_palette_count;
extern const u16 shmup_bullet_palettes[];
extern const u8 shmup_bullet_pal_base;
extern const u16 shmup_bullet_tile_base;

extern const NgpcMetasprite shmup_bullet_frame_0;

extern const MsprAnimFrame shmup_bullet_anim[];
extern const u8 shmup_bullet_anim_count;

#endif /* SHMUP_BULLET_MSPR_H */
