/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 shmup_ast3_tiles_count = 16u;
const u16 shmup_ast3_tiles[] = {
    0x27C0, 0x95F0, 0x9970, 0xA670, 0xA65C, 0x2D5C, 0x295C, 0x0A5C, 0x0A5C, 0x0A57, 0x0957, 0x0995,
    0x0A65, 0x0AD5, 0x0AA8, 0x02A0
};

const u8 shmup_ast3_palette_count = 1u;
const u16 shmup_ast3_palettes[] = {
    0x0000, 0x0455, 0x0521, 0x00AF
};

const u8 shmup_ast3_pal_base = 9u;

const u16 shmup_ast3_tile_base = 306u;

const NgpcMetasprite shmup_ast3_frame_0 = {
    2u, 8u, 16u,
    {
        { 0, 0, 306, 9, 0 },
        { 0, 8, 307, 9, 0 }
    }
};

const MsprAnimFrame shmup_ast3_anim[] = {
    { &shmup_ast3_frame_0, 6 }
};

const u8 shmup_ast3_anim_count = 1u;
