/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef SHMUP_TRAIL_MSPR_H
#define SHMUP_TRAIL_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 shmup_trail_tiles_count;
extern const u16 shmup_trail_tiles[];

extern const u8 shmup_trail_palette_count;
extern const u16 shmup_trail_palettes[];
extern const u8 shmup_trail_pal_base;
extern const u16 shmup_trail_tile_base;

extern const NgpcMetasprite shmup_trail_frame_0;
extern const NgpcMetasprite shmup_trail_frame_1;
extern const NgpcMetasprite shmup_trail_frame_2;

extern const MsprAnimFrame shmup_trail_anim[];
extern const u8 shmup_trail_anim_count;

#endif /* SHMUP_TRAIL_MSPR_H */
