/* Generated by ngpc_tilemap.py - do not edit */

#ifndef SHMUP_BG_TILEMAP_H
#define SHMUP_BG_TILEMAP_H

#include "ngpc_types.h"

extern const u8 shmup_bg_map_w;
extern const u8 shmup_bg_map_h;
extern const u16 shmup_bg_map_len;

extern const u8 shmup_bg_palette_count;
extern const u16 shmup_bg_palettes[];

extern const u16 shmup_bg_tiles_count;
extern const u16 shmup_bg_tiles[];

extern const u16 shmup_bg_map_tiles[];
extern const u8 shmup_bg_map_pals[];

#endif /* SHMUP_BG_TILEMAP_H */
