/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 shmup_ast2_tiles_count = 32u;
const u16 shmup_ast2_tiles[] = {
    0x0000, 0x0000, 0x0017, 0x0069, 0x0256, 0x02D6, 0x0275, 0x0295, 0x0000, 0x0000, 0xC000, 0xF000,
    0x7C00, 0x5F00, 0x5700, 0x6500, 0x0095, 0x00A5, 0x00A5, 0x0029, 0x000A, 0x0000, 0x0000, 0x0000,
    0x5B00, 0xD500, 0x5800, 0x6800, 0xA000, 0x0000, 0x0000, 0x0000
};

const u8 shmup_ast2_palette_count = 1u;
const u16 shmup_ast2_palettes[] = {
    0x0000, 0x0455, 0x0521, 0x00AF
};

const u8 shmup_ast2_pal_base = 9u;

const u16 shmup_ast2_tile_base = 302u;

const NgpcMetasprite shmup_ast2_frame_0 = {
    4u, 16u, 16u,
    {
        { 0, 0, 302, 9, 0 },
        { 8, 0, 303, 9, 0 },
        { 0, 8, 304, 9, 0 },
        { 8, 8, 305, 9, 0 }
    }
};

const MsprAnimFrame shmup_ast2_anim[] = {
    { &shmup_ast2_frame_0, 6 }
};

const u8 shmup_ast2_anim_count = 1u;
