/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 shmup_ast5_tiles_count = 8u;
const u16 shmup_ast5_tiles[] = {
    0x0970, 0x256C, 0x2554, 0x2554, 0x2554, 0x0958, 0x02A0, 0x0000
};

const u8 shmup_ast5_palette_count = 1u;
const u16 shmup_ast5_palettes[] = {
    0x0000, 0x0455, 0x0521, 0x00AF
};

const u8 shmup_ast5_pal_base = 9u;

const u16 shmup_ast5_tile_base = 310u;

const NgpcMetasprite shmup_ast5_frame_0 = {
    1u, 8u, 8u,
    {
        { 0, 0, 310, 9, 0 }
    }
};

const MsprAnimFrame shmup_ast5_anim[] = {
    { &shmup_ast5_frame_0, 6 }
};

const u8 shmup_ast5_anim_count = 1u;
