/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef SHMUP_BOSS2_MSPR_H
#define SHMUP_BOSS2_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 shmup_boss2_tiles_count;
extern const u16 shmup_boss2_tiles[];

extern const u8 shmup_boss2_palette_count;
extern const u16 shmup_boss2_palettes[];
extern const u8 shmup_boss2_pal_base;
extern const u16 shmup_boss2_tile_base;

extern const NgpcMetasprite shmup_boss2_frame_0;

extern const MsprAnimFrame shmup_boss2_anim[];
extern const u8 shmup_boss2_anim_count;

#endif /* SHMUP_BOSS2_MSPR_H */
