/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 shmup_player_b_tiles_count = 96u;
const u16 shmup_player_b_tiles[] = {
    0x0000, 0x0000, 0x0000, 0x0000, 0x0004, 0x1401, 0x1401, 0x0410, 0x0000, 0x0000, 0x0000, 0x0000,
    0x1400, 0xF800, 0xFC00, 0xFC00, 0x008A, 0x0204, 0x1204, 0x0022, 0x0020, 0x0000, 0x0000, 0x0000,
    0xF800, 0x2800, 0x1400, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0020, 0x0020, 0x0022, 0x1204,
    0x0204, 0x008A, 0x1410, 0x0401, 0x0000, 0x0000, 0x0000, 0x1400, 0x0000, 0x2800, 0xF800, 0xFC00,
    0x0401, 0x1410, 0x008A, 0x0204, 0x1204, 0x0022, 0x0020, 0x0020, 0xFC00, 0xF800, 0x2800, 0x0000,
    0x1400, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0020, 0x0022, 0x1204, 0x0204, 0x008A,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x1400, 0x2800, 0xF800, 0x0410, 0x1401, 0x1401, 0x0004,
    0x0000, 0x0000, 0x0000, 0x0000, 0xFC00, 0xFC00, 0xF800, 0x1400, 0x0000, 0x0000, 0x0000, 0x0000
};

const u8 shmup_player_b_palette_count = 1u;
const u16 shmup_player_b_palettes[] = {
    0x0000, 0x0657, 0x044F, 0x0112
};

const u8 shmup_player_b_pal_base = 1u;

const u16 shmup_player_b_tile_base = 268u;

const NgpcMetasprite shmup_player_b_frame_0 = {
    4u, 16u, 16u,
    {
        { 0, 0, 268, 1, 0 },
        { 8, 0, 269, 1, 0 },
        { 0, 8, 270, 1, 0 },
        { 8, 8, 271, 1, 0 }
    }
};

const NgpcMetasprite shmup_player_b_frame_1 = {
    4u, 16u, 16u,
    {
        { 0, 0, 272, 1, 0 },
        { 8, 0, 273, 1, 0 },
        { 0, 8, 274, 1, 0 },
        { 8, 8, 275, 1, 0 }
    }
};

const NgpcMetasprite shmup_player_b_frame_2 = {
    4u, 16u, 16u,
    {
        { 0, 0, 276, 1, 0 },
        { 8, 0, 277, 1, 0 },
        { 0, 8, 278, 1, 0 },
        { 8, 8, 279, 1, 0 }
    }
};

const MsprAnimFrame shmup_player_b_anim[] = {
    { &shmup_player_b_frame_0, 6 },
    { &shmup_player_b_frame_1, 6 },
    { &shmup_player_b_frame_2, 6 }
};

const u8 shmup_player_b_anim_count = 3u;
