/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 shmup_explosion_tiles_count = 24u;
const u16 shmup_explosion_tiles[] = {
    0x355C, 0xD697, 0x5AA5, 0x6AA9, 0x6AA9, 0x5AA5, 0xD697, 0x355C, 0x0000, 0x0000, 0x0D70, 0x0690,
    0x0690, 0x0D70, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0E40, 0x0D40, 0x0000, 0x0000, 0x0000
};

const u8 shmup_explosion_palette_count = 1u;
const u16 shmup_explosion_palettes[] = {
    0x0000, 0x02EF, 0x0EFF, 0x0527
};

const u8 shmup_explosion_pal_base = 6u;

const u16 shmup_explosion_tile_base = 286u;

const NgpcMetasprite shmup_explosion_frame_0 = {
    1u, 8u, 8u,
    {
        { 0, 0, 286, 6, 0 }
    }
};

const NgpcMetasprite shmup_explosion_frame_1 = {
    1u, 8u, 8u,
    {
        { 0, 0, 287, 6, 0 }
    }
};

const NgpcMetasprite shmup_explosion_frame_2 = {
    1u, 8u, 8u,
    {
        { 0, 0, 288, 6, 0 }
    }
};

const MsprAnimFrame shmup_explosion_anim[] = {
    { &shmup_explosion_frame_0, 3 },
    { &shmup_explosion_frame_1, 3 },
    { &shmup_explosion_frame_2, 3 }
};

const u8 shmup_explosion_anim_count = 3u;
