/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 shmup_enemy1_tiles_count = 8u;
const u16 shmup_enemy1_tiles[] = {
    0x2590, 0x5651, 0x0954, 0x03D4, 0x03D4, 0x0954, 0x5651, 0x2590
};

const u8 shmup_enemy1_palette_count = 1u;
const u16 shmup_enemy1_palettes[] = {
    0x0000, 0x0978, 0x0521, 0x0527
};

const u8 shmup_enemy1_pal_base = 2u;

const u16 shmup_enemy1_tile_base = 280u;

const NgpcMetasprite shmup_enemy1_frame_0 = {
    1u, 8u, 8u,
    {
        { 0, 0, 280, 2, 0 }
    }
};

const MsprAnimFrame shmup_enemy1_anim[] = {
    { &shmup_enemy1_frame_0, 6 }
};

const u8 shmup_enemy1_anim_count = 1u;
