/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 shmup_enemy2_tiles_count = 8u;
const u16 shmup_enemy2_tiles[] = {
    0x0540, 0x1554, 0x0D5C, 0x5695, 0x5695, 0x0D5C, 0x1554, 0x0540
};

const u8 shmup_enemy2_palette_count = 1u;
const u16 shmup_enemy2_palettes[] = {
    0x0000, 0x0FFF, 0x000D, 0x0322
};

const u8 shmup_enemy2_pal_base = 3u;

const u16 shmup_enemy2_tile_base = 281u;

const NgpcMetasprite shmup_enemy2_frame_0 = {
    1u, 8u, 8u,
    {
        { 0, 0, 281, 3, 0 }
    }
};

const MsprAnimFrame shmup_enemy2_anim[] = {
    { &shmup_enemy2_frame_0, 6 }
};

const u8 shmup_enemy2_anim_count = 1u;
