/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef SHMUP_BULLET2_MSPR_H
#define SHMUP_BULLET2_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 shmup_bullet2_tiles_count;
extern const u16 shmup_bullet2_tiles[];

extern const u8 shmup_bullet2_palette_count;
extern const u16 shmup_bullet2_palettes[];
extern const u8 shmup_bullet2_pal_base;
extern const u16 shmup_bullet2_tile_base;

extern const NgpcMetasprite shmup_bullet2_frame_0;

extern const MsprAnimFrame shmup_bullet2_anim[];
extern const u8 shmup_bullet2_anim_count;

#endif /* SHMUP_BULLET2_MSPR_H */
