/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef SHMUP_ENEMY2_MSPR_H
#define SHMUP_ENEMY2_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 shmup_enemy2_tiles_count;
extern const u16 shmup_enemy2_tiles[];

extern const u8 shmup_enemy2_palette_count;
extern const u16 shmup_enemy2_palettes[];
extern const u8 shmup_enemy2_pal_base;
extern const u16 shmup_enemy2_tile_base;

extern const NgpcMetasprite shmup_enemy2_frame_0;

extern const MsprAnimFrame shmup_enemy2_anim[];
extern const u8 shmup_enemy2_anim_count;

#endif /* SHMUP_ENEMY2_MSPR_H */
