/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef SHMUP_AST2_MSPR_H
#define SHMUP_AST2_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 shmup_ast2_tiles_count;
extern const u16 shmup_ast2_tiles[];

extern const u8 shmup_ast2_palette_count;
extern const u16 shmup_ast2_palettes[];
extern const u8 shmup_ast2_pal_base;
extern const u16 shmup_ast2_tile_base;

extern const NgpcMetasprite shmup_ast2_frame_0;

extern const MsprAnimFrame shmup_ast2_anim[];
extern const u8 shmup_ast2_anim_count;

#endif /* SHMUP_AST2_MSPR_H */
