/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 shmup_option_a_tiles_count = 8u;
const u16 shmup_option_a_tiles[] = {
    0x0550, 0x1144, 0x4411, 0x5005, 0x5005, 0x4411, 0x1144, 0x0550
};

const u8 shmup_option_a_palette_count = 1u;
const u16 shmup_option_a_palettes[] = {
    0x0000, 0x0219, 0x0FFF, 0x09AB
};

const u8 shmup_option_a_pal_base = 0u;

const u16 shmup_option_a_tile_base = 284u;

const NgpcMetasprite shmup_option_a_frame_0 = {
    1u, 8u, 8u,
    {
        { 0, 0, 284, 0, 0 }
    }
};

const MsprAnimFrame shmup_option_a_anim[] = {
    { &shmup_option_a_frame_0, 1 }
};

const u8 shmup_option_a_anim_count = 1u;
