/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef SHMUP_AST3_MSPR_H
#define SHMUP_AST3_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 shmup_ast3_tiles_count;
extern const u16 shmup_ast3_tiles[];

extern const u8 shmup_ast3_palette_count;
extern const u16 shmup_ast3_palettes[];
extern const u8 shmup_ast3_pal_base;
extern const u16 shmup_ast3_tile_base;

extern const NgpcMetasprite shmup_ast3_frame_0;

extern const MsprAnimFrame shmup_ast3_anim[];
extern const u8 shmup_ast3_anim_count;

#endif /* SHMUP_AST3_MSPR_H */
