/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 shmup_ast1_tiles_count = 32u;
const u16 shmup_ast1_tiles[] = {
    0x0000, 0x0000, 0x0000, 0x0029, 0x00A5, 0x02A5, 0x0295, 0x0295, 0x0000, 0x0000, 0x5F00, 0x57C0,
    0x59F0, 0x7570, 0x5570, 0xA570, 0x0A97, 0x0A97, 0x0AA5, 0x0AA5, 0x02A9, 0x00AA, 0x0000, 0x0000,
    0x5950, 0x5960, 0xF580, 0x5600, 0x5800, 0x8000, 0x0000, 0x0000
};

const u8 shmup_ast1_palette_count = 1u;
const u16 shmup_ast1_palettes[] = {
    0x0000, 0x0455, 0x0521, 0x00AF
};

const u8 shmup_ast1_pal_base = 9u;

const u16 shmup_ast1_tile_base = 298u;

const NgpcMetasprite shmup_ast1_frame_0 = {
    4u, 16u, 16u,
    {
        { 0, 0, 298, 9, 0 },
        { 8, 0, 299, 9, 0 },
        { 0, 8, 300, 9, 0 },
        { 8, 8, 301, 9, 0 }
    }
};

const MsprAnimFrame shmup_ast1_anim[] = {
    { &shmup_ast1_frame_0, 6 }
};

const u8 shmup_ast1_anim_count = 1u;
