/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef SHMUP_ENEMY1_MSPR_H
#define SHMUP_ENEMY1_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 shmup_enemy1_tiles_count;
extern const u16 shmup_enemy1_tiles[];

extern const u8 shmup_enemy1_palette_count;
extern const u16 shmup_enemy1_palettes[];
extern const u8 shmup_enemy1_pal_base;
extern const u16 shmup_enemy1_tile_base;

extern const NgpcMetasprite shmup_enemy1_frame_0;

extern const MsprAnimFrame shmup_enemy1_anim[];
extern const u8 shmup_enemy1_anim_count;

#endif /* SHMUP_ENEMY1_MSPR_H */
