/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef SHMUP_PLAYER_B_MSPR_H
#define SHMUP_PLAYER_B_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 shmup_player_b_tiles_count;
extern const u16 shmup_player_b_tiles[];

extern const u8 shmup_player_b_palette_count;
extern const u16 shmup_player_b_palettes[];
extern const u8 shmup_player_b_pal_base;
extern const u16 shmup_player_b_tile_base;

extern const NgpcMetasprite shmup_player_b_frame_0;
extern const NgpcMetasprite shmup_player_b_frame_1;
extern const NgpcMetasprite shmup_player_b_frame_2;

extern const MsprAnimFrame shmup_player_b_anim[];
extern const u8 shmup_player_b_anim_count;

#endif /* SHMUP_PLAYER_B_MSPR_H */
