/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 shmup_drop_final_tiles_count = 8u;
const u16 shmup_drop_final_tiles[] = {
    0x0550, 0x1554, 0x5695, 0x5AA5, 0x5AA5, 0x5695, 0x1554, 0x0550
};

const u8 shmup_drop_final_palette_count = 1u;
const u16 shmup_drop_final_palettes[] = {
    0x0000, 0x0570, 0x02C7, 0x0000
};

const u8 shmup_drop_final_pal_base = 10u;

const u16 shmup_drop_final_tile_base = 338u;

const NgpcMetasprite shmup_drop_final_frame_0 = {
    1u, 8u, 8u,
    {
        { 0, 0, 338, 10, 0 }
    }
};

const MsprAnimFrame shmup_drop_final_anim[] = {
    { &shmup_drop_final_frame_0, 6 }
};

const u8 shmup_drop_final_anim_count = 1u;
