/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef SHMUP_AST5_MSPR_H
#define SHMUP_AST5_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 shmup_ast5_tiles_count;
extern const u16 shmup_ast5_tiles[];

extern const u8 shmup_ast5_palette_count;
extern const u16 shmup_ast5_palettes[];
extern const u8 shmup_ast5_pal_base;
extern const u16 shmup_ast5_tile_base;

extern const NgpcMetasprite shmup_ast5_frame_0;

extern const MsprAnimFrame shmup_ast5_anim[];
extern const u8 shmup_ast5_anim_count;

#endif /* SHMUP_AST5_MSPR_H */
