/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 shmup_player_a_tiles_count = 96u;
const u16 shmup_player_a_tiles[] = {
    0x0000, 0x0000, 0x0050, 0x0554, 0x3573, 0x02B8, 0x02B8, 0x03CD, 0x0000, 0x0000, 0x0000, 0x0000,
    0xC300, 0x0100, 0x02AC, 0x02AC, 0x3510, 0x3462, 0x0462, 0x0544, 0x0044, 0x0050, 0x0000, 0x0000,
    0x03C0, 0x8100, 0x8300, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0040, 0x0044, 0x0044, 0x0462,
    0x3462, 0x3510, 0x03CD, 0x02B8, 0x0000, 0x0000, 0x0000, 0x8300, 0x8000, 0x4100, 0x03C0, 0x02AC,
    0x02B8, 0x03CD, 0x3510, 0x3462, 0x0462, 0x0044, 0x0044, 0x0040, 0x02AC, 0x03C0, 0x4100, 0x8000,
    0x8300, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0050, 0x0044, 0x0544, 0x0462, 0x3462, 0x3510,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x8300, 0x8100, 0x03C0, 0x03CD, 0x02B8, 0x02B8, 0x3573,
    0x0554, 0x0050, 0x0000, 0x0000, 0x02AC, 0x02AC, 0x0100, 0xC300, 0x0000, 0x0000, 0x0000, 0x0000
};

const u8 shmup_player_a_palette_count = 1u;
const u16 shmup_player_a_palettes[] = {
    0x0000, 0x0219, 0x0FFF, 0x09AB
};

const u8 shmup_player_a_pal_base = 0u;

const u16 shmup_player_a_tile_base = 256u;

const NgpcMetasprite shmup_player_a_frame_0 = {
    4u, 16u, 16u,
    {
        { 0, 0, 256, 0, 0 },
        { 8, 0, 257, 0, 0 },
        { 0, 8, 258, 0, 0 },
        { 8, 8, 259, 0, 0 }
    }
};

const NgpcMetasprite shmup_player_a_frame_1 = {
    4u, 16u, 16u,
    {
        { 0, 0, 260, 0, 0 },
        { 8, 0, 261, 0, 0 },
        { 0, 8, 262, 0, 0 },
        { 8, 8, 263, 0, 0 }
    }
};

const NgpcMetasprite shmup_player_a_frame_2 = {
    4u, 16u, 16u,
    {
        { 0, 0, 264, 0, 0 },
        { 8, 0, 265, 0, 0 },
        { 0, 8, 266, 0, 0 },
        { 8, 8, 267, 0, 0 }
    }
};

const MsprAnimFrame shmup_player_a_anim[] = {
    { &shmup_player_a_frame_0, 6 },
    { &shmup_player_a_frame_1, 6 },
    { &shmup_player_a_frame_2, 6 }
};

const u8 shmup_player_a_anim_count = 3u;
