/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 shmup_bullet2_tiles_count = 8u;
const u16 shmup_bullet2_tiles[] = {
    0x0000, 0x211C, 0x0000, 0x0000, 0x0000, 0x0000, 0x211C, 0x0000
};

const u8 shmup_bullet2_palette_count = 1u;
const u16 shmup_bullet2_palettes[] = {
    0x0000, 0x03E0, 0x0580, 0x0EFF
};

const u8 shmup_bullet2_pal_base = 5u;

const u16 shmup_bullet2_tile_base = 355u;

const NgpcMetasprite shmup_bullet2_frame_0 = {
    1u, 8u, 8u,
    {
        { 0, 0, 355, 5, 0 }
    }
};

const MsprAnimFrame shmup_bullet2_anim[] = {
    { &shmup_bullet2_frame_0, 3 }
};

const u8 shmup_bullet2_anim_count = 1u;
