/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef SHMUP_EXPLOSION_MSPR_H
#define SHMUP_EXPLOSION_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 shmup_explosion_tiles_count;
extern const u16 shmup_explosion_tiles[];

extern const u8 shmup_explosion_palette_count;
extern const u16 shmup_explosion_palettes[];
extern const u8 shmup_explosion_pal_base;
extern const u16 shmup_explosion_tile_base;

extern const NgpcMetasprite shmup_explosion_frame_0;
extern const NgpcMetasprite shmup_explosion_frame_1;
extern const NgpcMetasprite shmup_explosion_frame_2;

extern const MsprAnimFrame shmup_explosion_anim[];
extern const u8 shmup_explosion_anim_count;

#endif /* SHMUP_EXPLOSION_MSPR_H */
