/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef SHMUP_OPTION_A_MSPR_H
#define SHMUP_OPTION_A_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 shmup_option_a_tiles_count;
extern const u16 shmup_option_a_tiles[];

extern const u8 shmup_option_a_palette_count;
extern const u16 shmup_option_a_palettes[];
extern const u8 shmup_option_a_pal_base;
extern const u16 shmup_option_a_tile_base;

extern const NgpcMetasprite shmup_option_a_frame_0;

extern const MsprAnimFrame shmup_option_a_anim[];
extern const u8 shmup_option_a_anim_count;

#endif /* SHMUP_OPTION_A_MSPR_H */
