/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 shmup_ast4_tiles_count = 16u;
const u16 shmup_ast4_tiles[] = {
    0x001F, 0x0095, 0x00A5, 0x00A5, 0x00A5, 0x0029, 0x000A, 0x0002, 0xC000, 0x7400, 0x6D00, 0x5B00,
    0x5B00, 0x5700, 0xA500, 0xA800
};

const u8 shmup_ast4_palette_count = 1u;
const u16 shmup_ast4_palettes[] = {
    0x0000, 0x0455, 0x0521, 0x00AF
};

const u8 shmup_ast4_pal_base = 9u;

const u16 shmup_ast4_tile_base = 308u;

const NgpcMetasprite shmup_ast4_frame_0 = {
    2u, 16u, 8u,
    {
        { 0, 0, 308, 9, 0 },
        { 8, 0, 309, 9, 0 }
    }
};

const MsprAnimFrame shmup_ast4_anim[] = {
    { &shmup_ast4_frame_0, 6 }
};

const u8 shmup_ast4_anim_count = 1u;
