/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef SHMUP_ENEMY5_FAT_MSPR_H
#define SHMUP_ENEMY5_FAT_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 shmup_enemy5_fat_tiles_count;
extern const u16 shmup_enemy5_fat_tiles[];

extern const u8 shmup_enemy5_fat_palette_count;
extern const u16 shmup_enemy5_fat_palettes[];
extern const u8 shmup_enemy5_fat_pal_base;
extern const u16 shmup_enemy5_fat_tile_base;

extern const NgpcMetasprite shmup_enemy5_fat_frame_0;

extern const MsprAnimFrame shmup_enemy5_fat_anim[];
extern const u8 shmup_enemy5_fat_anim_count;

#endif /* SHMUP_ENEMY5_FAT_MSPR_H */
