/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 shmup_option_b_tiles_count = 8u;
const u16 shmup_option_b_tiles[] = {
    0x0000, 0x0410, 0x13C4, 0x0D70, 0x0D70, 0x13C4, 0x0410, 0x0000
};

const u8 shmup_option_b_palette_count = 1u;
const u16 shmup_option_b_palettes[] = {
    0x0000, 0x0657, 0x044F, 0x0112
};

const u8 shmup_option_b_pal_base = 1u;

const u16 shmup_option_b_tile_base = 285u;

const NgpcMetasprite shmup_option_b_frame_0 = {
    1u, 8u, 8u,
    {
        { 0, 0, 285, 1, 0 }
    }
};

const MsprAnimFrame shmup_option_b_anim[] = {
    { &shmup_option_b_frame_0, 1 }
};

const u8 shmup_option_b_anim_count = 1u;
