/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef SHMUP_AST4_MSPR_H
#define SHMUP_AST4_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 shmup_ast4_tiles_count;
extern const u16 shmup_ast4_tiles[];

extern const u8 shmup_ast4_palette_count;
extern const u16 shmup_ast4_palettes[];
extern const u8 shmup_ast4_pal_base;
extern const u16 shmup_ast4_tile_base;

extern const NgpcMetasprite shmup_ast4_frame_0;

extern const MsprAnimFrame shmup_ast4_anim[];
extern const u8 shmup_ast4_anim_count;

#endif /* SHMUP_AST4_MSPR_H */
