/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 shmup_trail_tiles_count = 24u;
const u16 shmup_trail_tiles[] = {
    0x0000, 0x0000, 0x02D8, 0x2354, 0x8E54, 0x02D8, 0x0000, 0x0000, 0x0000, 0x0000, 0x02D8, 0x8E54,
    0x2354, 0x02D8, 0x0000, 0x0000, 0x0000, 0x0000, 0x0028, 0x02D4, 0x3394, 0x0028, 0x0000, 0x0000
};

const u8 shmup_trail_palette_count = 1u;
const u16 shmup_trail_palettes[] = {
    0x0000, 0x00AF, 0x0527, 0x040F
};

const u8 shmup_trail_pal_base = 7u;

const u16 shmup_trail_tile_base = 289u;

const NgpcMetasprite shmup_trail_frame_0 = {
    1u, 8u, 8u,
    {
        { 0, 0, 289, 7, 0 }
    }
};

const NgpcMetasprite shmup_trail_frame_1 = {
    1u, 8u, 8u,
    {
        { 0, 0, 290, 7, 0 }
    }
};

const NgpcMetasprite shmup_trail_frame_2 = {
    1u, 8u, 8u,
    {
        { 0, 0, 291, 7, 0 }
    }
};

const MsprAnimFrame shmup_trail_anim[] = {
    { &shmup_trail_frame_0, 2 },
    { &shmup_trail_frame_1, 2 },
    { &shmup_trail_frame_2, 2 }
};

const u8 shmup_trail_anim_count = 3u;
