/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 ui_digits_tiles_count = 80u;
const u16 ui_digits_tiles[] = {
    0x0000, 0x0140, 0x0410, 0x0450, 0x0510, 0x0410, 0x0140, 0x0000, 0x0000, 0x0040, 0x0140, 0x0040,
    0x0040, 0x0040, 0x0150, 0x0000, 0x0000, 0x0150, 0x0410, 0x0010, 0x0040, 0x0100, 0x0550, 0x0000,
    0x0000, 0x0550, 0x0010, 0x0140, 0x0010, 0x0010, 0x0540, 0x0000, 0x0000, 0x0140, 0x0140, 0x0440,
    0x1040, 0x1550, 0x0040, 0x0000, 0x0000, 0x0550, 0x0400, 0x0540, 0x0010, 0x0010, 0x0540, 0x0000,
    0x0000, 0x0150, 0x0500, 0x0550, 0x0410, 0x0410, 0x0140, 0x0000, 0x0000, 0x0550, 0x0010, 0x0040,
    0x0040, 0x0100, 0x0100, 0x0000, 0x0000, 0x0550, 0x0410, 0x0140, 0x0410, 0x0410, 0x0540, 0x0000,
    0x0000, 0x0140, 0x0410, 0x0410, 0x0550, 0x0010, 0x0540, 0x0000
};

const u8 ui_digits_palette_count = 1u;
const u16 ui_digits_palettes[] = {
    0x0000, 0x0570, 0x0000, 0x0000
};

const u8 ui_digits_pal_base = 10u;

const u16 ui_digits_tile_base = 323u;

const NgpcMetasprite ui_digits_frame_0 = {
    1u, 8u, 8u,
    {
        { 0, 0, 323, 10, 0 }
    }
};

const NgpcMetasprite ui_digits_frame_1 = {
    1u, 8u, 8u,
    {
        { 0, 0, 324, 10, 0 }
    }
};

const NgpcMetasprite ui_digits_frame_2 = {
    1u, 8u, 8u,
    {
        { 0, 0, 325, 10, 0 }
    }
};

const NgpcMetasprite ui_digits_frame_3 = {
    1u, 8u, 8u,
    {
        { 0, 0, 326, 10, 0 }
    }
};

const NgpcMetasprite ui_digits_frame_4 = {
    1u, 8u, 8u,
    {
        { 0, 0, 327, 10, 0 }
    }
};

const NgpcMetasprite ui_digits_frame_5 = {
    1u, 8u, 8u,
    {
        { 0, 0, 328, 10, 0 }
    }
};

const NgpcMetasprite ui_digits_frame_6 = {
    1u, 8u, 8u,
    {
        { 0, 0, 329, 10, 0 }
    }
};

const NgpcMetasprite ui_digits_frame_7 = {
    1u, 8u, 8u,
    {
        { 0, 0, 330, 10, 0 }
    }
};

const NgpcMetasprite ui_digits_frame_8 = {
    1u, 8u, 8u,
    {
        { 0, 0, 331, 10, 0 }
    }
};

const NgpcMetasprite ui_digits_frame_9 = {
    1u, 8u, 8u,
    {
        { 0, 0, 332, 10, 0 }
    }
};

const MsprAnimFrame ui_digits_anim[] = {
    { &ui_digits_frame_0, 1 },
    { &ui_digits_frame_1, 1 },
    { &ui_digits_frame_2, 1 },
    { &ui_digits_frame_3, 1 },
    { &ui_digits_frame_4, 1 },
    { &ui_digits_frame_5, 1 },
    { &ui_digits_frame_6, 1 },
    { &ui_digits_frame_7, 1 },
    { &ui_digits_frame_8, 1 },
    { &ui_digits_frame_9, 1 }
};

const u8 ui_digits_anim_count = 10u;
