/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef UI_DIGITS_MSPR_H
#define UI_DIGITS_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 ui_digits_tiles_count;
extern const u16 ui_digits_tiles[];

extern const u8 ui_digits_palette_count;
extern const u16 ui_digits_palettes[];
extern const u8 ui_digits_pal_base;
extern const u16 ui_digits_tile_base;

extern const NgpcMetasprite ui_digits_frame_0;
extern const NgpcMetasprite ui_digits_frame_1;
extern const NgpcMetasprite ui_digits_frame_2;
extern const NgpcMetasprite ui_digits_frame_3;
extern const NgpcMetasprite ui_digits_frame_4;
extern const NgpcMetasprite ui_digits_frame_5;
extern const NgpcMetasprite ui_digits_frame_6;
extern const NgpcMetasprite ui_digits_frame_7;
extern const NgpcMetasprite ui_digits_frame_8;
extern const NgpcMetasprite ui_digits_frame_9;

extern const MsprAnimFrame ui_digits_anim[];
extern const u8 ui_digits_anim_count;

#endif /* UI_DIGITS_MSPR_H */
