/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef UI_GAME_OVER_MSPR_H
#define UI_GAME_OVER_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 ui_game_over_tiles_count;
extern const u16 ui_game_over_tiles[];

extern const u8 ui_game_over_palette_count;
extern const u16 ui_game_over_palettes[];
extern const u8 ui_game_over_pal_base;
extern const u16 ui_game_over_tile_base;

extern const NgpcMetasprite ui_game_over_frame_0;

extern const MsprAnimFrame ui_game_over_anim[];
extern const u8 ui_game_over_anim_count;

#endif /* UI_GAME_OVER_MSPR_H */
