/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 ui_game_over_tiles_count = 56u;
const u16 ui_game_over_tiles[] = {
    0x0000, 0x0550, 0x16A8, 0x1654, 0x1616, 0x055A, 0x02A8, 0x0000, 0x0000, 0x0550, 0x1694, 0x1616,
    0x1556, 0x1696, 0x0A0A, 0x0000, 0x0000, 0x1414, 0x1556, 0x1556, 0x1696, 0x1616, 0x0A0A, 0x0000,
    0x0000, 0x1554, 0x16AA, 0x1550, 0x16A8, 0x1554, 0x0AAA, 0x0000, 0x0000, 0x0550, 0x1694, 0x1616,
    0x1616, 0x055A, 0x02A8, 0x0000, 0x0000, 0x1414, 0x1616, 0x055A, 0x0558, 0x0168, 0x00A0, 0x0000,
    0x0000, 0x1550, 0x1694, 0x155A, 0x1694, 0x1616, 0x0A0A, 0x0000
};

const u8 ui_game_over_palette_count = 1u;
const u16 ui_game_over_palettes[] = {
    0x0000, 0x044F, 0x0219, 0x0000
};

const u8 ui_game_over_pal_base = 11u;

const u16 ui_game_over_tile_base = 316u;

const NgpcMetasprite ui_game_over_frame_0 = {
    8u, 72u, 8u,
    {
        { 0, 0, 316, 11, 0 },
        { 8, 0, 317, 11, 0 },
        { 16, 0, 318, 11, 0 },
        { 24, 0, 319, 11, 0 },
        { 40, 0, 320, 11, 0 },
        { 48, 0, 321, 11, 0 },
        { 56, 0, 319, 11, 0 },
        { 64, 0, 322, 11, 0 }
    }
};

const MsprAnimFrame ui_game_over_anim[] = {
    { &ui_game_over_frame_0, 30 }
};

const u8 ui_game_over_anim_count = 1u;
