/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 ui_lifebar_tiles_count = 8u;
const u16 ui_lifebar_tiles[] = {
    0xA800, 0x9800, 0x9800, 0x9800, 0x9800, 0x9800, 0x9800, 0xA800
};

const u8 ui_lifebar_palette_count = 1u;
const u16 ui_lifebar_palettes[] = {
    0x0000, 0x03E0, 0x0580, 0x0EFF
};

const u8 ui_lifebar_pal_base = 5u;

const u16 ui_lifebar_tile_base = 356u;

const NgpcMetasprite ui_lifebar_frame_0 = {
    1u, 8u, 8u,
    {
        { 0, 0, 356, 5, 0 }
    }
};

const MsprAnimFrame ui_lifebar_anim[] = {
    { &ui_lifebar_frame_0, 1 }
};

const u8 ui_lifebar_anim_count = 1u;
