/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef UI_LIFEBAR_MSPR_H
#define UI_LIFEBAR_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 ui_lifebar_tiles_count;
extern const u16 ui_lifebar_tiles[];

extern const u8 ui_lifebar_palette_count;
extern const u16 ui_lifebar_palettes[];
extern const u8 ui_lifebar_pal_base;
extern const u16 ui_lifebar_tile_base;

extern const NgpcMetasprite ui_lifebar_frame_0;

extern const MsprAnimFrame ui_lifebar_anim[];
extern const u8 ui_lifebar_anim_count;

#endif /* UI_LIFEBAR_MSPR_H */
