/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef UI_POWERUP_MSPR_H
#define UI_POWERUP_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 ui_powerup_tiles_count;
extern const u16 ui_powerup_tiles[];

extern const u8 ui_powerup_palette_count;
extern const u16 ui_powerup_palettes[];
extern const u8 ui_powerup_pal_base;
extern const u16 ui_powerup_tile_base;

extern const NgpcMetasprite ui_powerup_frame_0;
extern const NgpcMetasprite ui_powerup_frame_1;
extern const NgpcMetasprite ui_powerup_frame_2;
extern const NgpcMetasprite ui_powerup_frame_3;
extern const NgpcMetasprite ui_powerup_frame_4;

extern const MsprAnimFrame ui_powerup_anim[];
extern const u8 ui_powerup_anim_count;

#endif /* UI_POWERUP_MSPR_H */
