/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 ui_powerup_tiles_count = 40u;
const u16 ui_powerup_tiles[] = {
    0x0000, 0x0150, 0x0400, 0x0500, 0x0050, 0x0010, 0x0540, 0x0000, 0x0000, 0x0550, 0x0410, 0x0410,
    0x0540, 0x0400, 0x0400, 0x0000, 0x0000, 0x0540, 0x0410, 0x0410, 0x0410, 0x0410, 0x0540, 0x0000,
    0x0000, 0x0100, 0x0100, 0x0100, 0x0100, 0x0100, 0x0150, 0x0000, 0x0000, 0x0540, 0x1010, 0x1010,
    0x1010, 0x1010, 0x0540, 0x0000
};

const u8 ui_powerup_palette_count = 1u;
const u16 ui_powerup_palettes[] = {
    0x0000, 0x0570, 0x0000, 0x0000
};

const u8 ui_powerup_pal_base = 10u;

const u16 ui_powerup_tile_base = 333u;

const NgpcMetasprite ui_powerup_frame_0 = {
    1u, 8u, 8u,
    {
        { 0, 0, 333, 10, 0 }
    }
};

const NgpcMetasprite ui_powerup_frame_1 = {
    1u, 8u, 8u,
    {
        { 0, 0, 334, 10, 0 }
    }
};

const NgpcMetasprite ui_powerup_frame_2 = {
    1u, 8u, 8u,
    {
        { 0, 0, 335, 10, 0 }
    }
};

const NgpcMetasprite ui_powerup_frame_3 = {
    1u, 8u, 8u,
    {
        { 0, 0, 336, 10, 0 }
    }
};

const NgpcMetasprite ui_powerup_frame_4 = {
    1u, 8u, 8u,
    {
        { 0, 0, 337, 10, 0 }
    }
};

const MsprAnimFrame ui_powerup_anim[] = {
    { &ui_powerup_frame_0, 1 },
    { &ui_powerup_frame_1, 1 },
    { &ui_powerup_frame_2, 1 },
    { &ui_powerup_frame_3, 1 },
    { &ui_powerup_frame_4, 1 }
};

const u8 ui_powerup_anim_count = 5u;
