/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 ui_start_tiles_count = 40u;
const u16 ui_start_tiles[] = {
    0x0000, 0x0554, 0x16AA, 0x0550, 0x0294, 0x155A, 0x0AA8, 0x0000, 0x0000, 0x1554, 0x096A, 0x0160,
    0x0160, 0x0160, 0x00A0, 0x0000, 0x0000, 0x0550, 0x1694, 0x1616, 0x1556, 0x1696, 0x0A0A, 0x0000,
    0x0000, 0x1550, 0x1694, 0x155A, 0x1694, 0x1616, 0x0A0A, 0x0000, 0x0000, 0x1400, 0x1600, 0x1600,
    0x0A00, 0x1400, 0x0A00, 0x0000
};

const u8 ui_start_palette_count = 1u;
const u16 ui_start_palettes[] = {
    0x0000, 0x02C7, 0x0570, 0x0000
};

const u8 ui_start_pal_base = 10u;

const u16 ui_start_tile_base = 311u;

const NgpcMetasprite ui_start_frame_0 = {
    6u, 48u, 8u,
    {
        { 0, 0, 311, 10, 0 },
        { 8, 0, 312, 10, 0 },
        { 16, 0, 313, 10, 0 },
        { 24, 0, 314, 10, 0 },
        { 32, 0, 312, 10, 0 },
        { 40, 0, 315, 10, 0 }
    }
};

const MsprAnimFrame ui_start_anim[] = {
    { &ui_start_frame_0, 30 }
};

const u8 ui_start_anim_count = 1u;
