/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef UI_START_MSPR_H
#define UI_START_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 ui_start_tiles_count;
extern const u16 ui_start_tiles[];

extern const u8 ui_start_palette_count;
extern const u16 ui_start_palettes[];
extern const u8 ui_start_pal_base;
extern const u16 ui_start_tile_base;

extern const NgpcMetasprite ui_start_frame_0;

extern const MsprAnimFrame ui_start_anim[];
extern const u8 ui_start_anim_count;

#endif /* UI_START_MSPR_H */
